postMerge :
  
  subModules:          #Not to be changed
        
      - name: agenda     
        path : "./"
        pattern: 
          - "./test/*.js"
        framework : mocha
        preRun:
          env:
            USE_MONGODB: true
          command:
            - curl -fsSL https://www.mongodb.org/static/pgp/server-4.4.asc |  apt-key add -
            - echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.4 multiverse" |  tee /etc/apt/sources.list.d/mongodb-org-4.4.list
            - apt-get update && apt-get install -y mongodb-org
            - mkdir -p /data/db
            - mongod --wiredTigerCacheSizeGB=0.5 &
            - yarn install
            - yarn run build
            
        runPreRunEveryTime: true

        postRun:
            command:
              - node --version 
        configFile : ".mocharc.yml"
       
      
preMerge : 
  
  subModules:          #Not to be changed

    - name: agenda     
      path : "./"
      pattern: 
        - "./test/*.js"

      framework : mocha
      preRun:
        command:
          - curl -fsSL https://www.mongodb.org/static/pgp/server-4.4.asc |  apt-key add -
          - echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.4 multiverse" |  tee /etc/apt/sources.list.d/mongodb-org-4.4.list
          - apt-get update && apt-get install -y mongodb-org
          - mongod &
          - yarn install
          - yarn run build
      
      runPreRunEveryTime: true
      postRun:
          command:
            - node --version 
      configFile : ".mocharc.yml"
      

version : 2.0.1


